/* Generated by Edge Impulse
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _EI_CLASSIFIER_IMPULSE_10_20_H_
#define _EI_CLASSIFIER_IMPULSE_10_20_H_

#include <stdint.h>
#include "tflite-model/tflite-trained_12_10.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"

namespace namespace_12_10 {
    const char* ei_classifier_inferencing_categories[] = { "faucet", "noise" };

    uint8_t ei_dsp_config_3_axes[] = { 0 };
    const uint32_t ei_dsp_config_3_axes_size = 1;
    ei_dsp_config_mfcc_t ei_dsp_config_3 = {
        3,
        1,
        13,
        0.02f,
        0.02f,
        32,
        256,
        101,
        300,
        0,
        0.98f,
        1
    };

    const size_t ei_dsp_blocks_size = 1;
    ei_model_dsp_t ei_dsp_blocks[ei_dsp_blocks_size] = {
        { // DSP block 3
            650,
            &extract_mfcc_features,
            (void*)&ei_dsp_config_3,
            ei_dsp_config_3_axes,
            ei_dsp_config_3_axes_size
        }
    };

    const ei_model_performance_calibration_t ei_calibration = {
        1, /* integer version number */
        false, /* has configured performance calibration */
        (int32_t)(16000 / 0.0625) * 1000, /* Model window */
        0.8f, /* Default threshold */
        (int32_t)(16000 / 0.0625) * 500, /* Half of model window */
        0   /* Don't use flags */
    };

} // impulse_12_20 namespace

const ei_impulse_t impulse_12_10 = {
    .project_id = 12,
    .project_owner = "Selenium test runner 9",
    .project_name = "selenium-automated-project-9",
    .deploy_version = 10,

    .nn_input_frame_size = 650,
    .raw_sample_count = 16000,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 16000 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 0.0625,
    .frequency = 16000,
    .use_quantized_dsp_block = 0,
    .dsp_blocks_size = namespace_12_10::ei_dsp_blocks_size,
    .dsp_blocks = namespace_12_10::ei_dsp_blocks,

    .has_anomaly = 0,
    .anom_axis = NULL,
    .anom_axes_size = NULL,
    .anom_clusters = NULL,
    .anom_cluster_count = NULL,
    .anom_scale = NULL,
    .anom_mean = NULL,

    .object_detection = 0,
    .object_detection_count = 0,
    .object_detection_threshold = 0,
    .object_detection_last_layer = EI_CLASSIFIER_LAST_LAYER_UNKNOWN,
    .tflite_output_labels_tensor = 0,
    .tflite_output_score_tensor = 0,
    .tflite_output_data_tensor = 0,

    .tflite_arena_size = 11468,
    .tflite_input_datatype = EI_CLASSIFIER_DATATYPE_INT8,
    .tflite_input_quantized = 1,
    .tflite_input_scale = 0.038505394011735916,
    .tflite_input_zeropoint = -19,
    .tflite_output_datatype = EI_CLASSIFIER_DATATYPE_INT8,
    .tflite_output_quantized = 1,
    .tflite_output_scale = 0.00390625,
    .tflite_output_zeropoint = -128,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,
    .compiled = 0,
    .has_tflite_ops_resolver = 1,

    .sensor = EI_CLASSIFIER_SENSOR_MICROPHONE,
    .fusion_string = "audio",

    .slice_size = (16000/4),
    .slices_per_model_window = 4,

    .model_arr = namespace_12_10::trained_tflite,
    .model_arr_size = namespace_12_10::trained_tflite_len,
    .model_input = NULL,
    .model_output = NULL,
    .model_init = NULL,
    .model_invoke = NULL,
    .model_reset = NULL,

    .label_count = 2,
    .calibration = namespace_12_10::ei_calibration,
    .categories = new const char*[4] { "faucet", "noise" }
};

#endif // _EI_CLASSIFIER_IMPULSE_10_20_H_